name: hello-world

on: push
  

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4

      - name: Print the content of hello_world.txt
        run: echo "$(cat hello_world.txt)"
      - name: Sleep for 15 sec
        run: sleep 15 
