name: hello-world

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4

      - name: Print the content of hello_world.txt
        run: echo "$(cat hello_world.txt)"
