name: hello-world

on: push

jobs:
  hello-world-job:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4
      - runs: echo "$(cat hello_world.txt)"
      
